"""Render the repository-grounded TrustOps README hero."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "images" / "trustops-social-preview.svg"

SOURCES = (
    ("AWS", "aws", "#ff9900"),
    ("Azure", "A", "#29a8ea"),
    ("GCP", "G", "#4285f4"),
    ("GitHub", "GH", "#f8fafc"),
    ("GitLab", "GL", "#fc6d26"),
    ("Okta", "O", "#38bdf8"),
    ("Snowflake", "✣", "#29b5e8"),
    ("ClickHouse", "▥", "#ffcc01"),
)

FRAMEWORKS = (
    ("SOC 2", 112),
    ("ISO 27001", 136),
    ("FedRAMP", 126),
    ("CMMC", 112),
    ("NIST CSF", 128),
    ("CIS AWS", 122),
)

STAGES = (
    ("01 · COLLECT", "Read-only evidence", "#6687ff"),
    ("02 · EVALUATE", "Deterministic tests", "#4d9ee4"),
    ("03 · OPERATE", "Findings + approvals", "#30b8c7"),
    ("04 · PROVE", "Immutable snapshots", "#2dd4bf"),
)


def _source_card(x: int, name: str, mark: str, accent: str) -> str:
    mark_size = 13 if len(mark) > 1 else 18
    return f"""    <g transform="translate({x} 302)">
      <rect width="124" height="66" rx="14" fill="#0e1a2d" stroke="#263954"/>
      <rect x="12" y="11" width="34" height="34" rx="10" fill="#111f34" stroke="{accent}" stroke-opacity="0.48"/>
      <text x="29" y="34" text-anchor="middle" font-size="{mark_size}" font-weight="850" fill="{accent}">{mark}</text>
      <text x="54" y="32" font-size="14" font-weight="760" fill="#e8f0fb">{name}</text>
      <circle cx="112" cy="14" r="3" fill="#2dd4bf"/>
      <text x="12" y="57" font-size="9" font-weight="700" letter-spacing="1.1" fill="#657993">READ ONLY</text>
    </g>"""


def _framework_pill(x: int, label: str, width: int) -> str:
    return f"""    <g transform="translate({x} 430)">
      <rect width="{width}" height="36" rx="18" fill="#0d1a2d" stroke="#36517a"/>
      <text x="{width / 2:g}" y="23" text-anchor="middle" font-size="13" font-weight="760" fill="#cbd8ea">{label}</text>
    </g>"""


def _stage_card(x: int, step: str, label: str, accent: str, final: bool) -> str:
    fill = "#e9fffd" if final else "#0f1c31"
    stroke = "#5eead4" if final else "#2d4361"
    step_fill = "#0f766e" if final else "#7890b2"
    label_fill = "#0b2c32" if final else "#f1f5fb"
    return f"""    <g transform="translate({x} 512)">
      <rect width="252" height="70" rx="15" fill="{fill}" stroke="{stroke}"/>
      <rect width="4" height="70" rx="2" fill="{accent}"/>
      <text x="22" y="28" font-size="10" font-weight="820" letter-spacing="1.5" fill="{step_fill}">{step}</text>
      <text x="22" y="52" font-size="16" font-weight="820" fill="{label_fill}">{label}</text>
    </g>"""


def _coverage_summary() -> tuple[int, int, int]:
    catalog = json.loads((ROOT / "controls" / "catalog.json").read_text(encoding="utf-8"))
    safeguard_registry = json.loads((ROOT / "controls" / "safeguards.json").read_text(encoding="utf-8"))
    controls = catalog["controls"]
    framework_count = len({control["framework_id"] for control in controls})
    return len(safeguard_registry["safeguards"]), len(controls), framework_count


def render_social_preview() -> str:
    safeguard_count, requirement_count, framework_count = _coverage_summary()
    source_cards = "\n".join(
        _source_card(62 + index * 136, name, mark, accent) for index, (name, mark, accent) in enumerate(SOURCES)
    )

    framework_pills: list[str] = []
    framework_x = 62
    framework_labels = (*FRAMEWORKS, (f"+ {framework_count - len(FRAMEWORKS)} packs", 116))
    for label, width in framework_labels:
        framework_pills.append(_framework_pill(framework_x, label, width))
        framework_x += width + 10

    stage_cards = "\n".join(
        _stage_card(62 + index * 274, step, label, accent, index == len(STAGES) - 1)
        for index, (step, label, accent) in enumerate(STAGES)
    )

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="title desc">
  <!-- Generated by tools/render_readme_header.py; do not edit by hand. -->
  <title id="title">TrustOps — collect, evaluate, and prove</title>
  <desc id="desc">Open-source trust operations across read-only cloud, identity, code, and data sources, with deterministic tests, a common control framework, governed findings, and immutable audit snapshots.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop stop-color="#050b14"/>
      <stop offset="0.58" stop-color="#091426"/>
      <stop offset="1" stop-color="#07323a"/>
    </linearGradient>
    <linearGradient id="mark" x1="0" y1="0" x2="1" y2="1">
      <stop stop-color="#718eff"/>
      <stop offset="1" stop-color="#2dd4bf"/>
    </linearGradient>
    <linearGradient id="accent" x1="62" y1="0" x2="1138" y2="0" gradientUnits="userSpaceOnUse">
      <stop stop-color="#6687ff"/>
      <stop offset="1" stop-color="#2dd4bf"/>
    </linearGradient>
    <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
      <path d="M40 0H0V40" fill="none" stroke="#80a4d6" stroke-opacity="0.055"/>
    </pattern>
    <filter id="glow" x="-60%" y="-60%" width="220%" height="220%">
      <feGaussianBlur stdDeviation="55"/>
    </filter>
    <style>
      .font {{ font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }}
    </style>
  </defs>
  <rect width="1200" height="630" rx="28" fill="url(#bg)"/>
  <rect width="1200" height="630" rx="28" fill="url(#grid)"/>
  <circle cx="1080" cy="50" r="170" fill="#2dd4bf" opacity="0.08" filter="url(#glow)"/>
  <path d="M974 0a238 238 0 0 0 226 238" fill="none" stroke="#4f7cff" stroke-width="2" opacity="0.13"/>
  <path d="M0 602c224-62 377 29 578-18s394-58 622-13v59H0Z" fill="#0da6a6" opacity="0.08"/>
  <g class="font">
    <g transform="translate(62 40)">
      <path d="M28 0 52 9v18c0 14-9.5 25-24 31C13.5 52 4 41 4 27V9L28 0Z" fill="url(#mark)"/>
      <path d="M16 17h24v7h-8v20h-8V24h-8v-7Z" fill="#fff"/>
      <path d="m35 42 4 4 9-11" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
    </g>
    <text x="130" y="80" font-size="34" font-weight="860" letter-spacing="-1.4" fill="#f8fafc">TrustOps</text>
    <text x="1138" y="62" text-anchor="end" font-size="11" font-weight="800" letter-spacing="1.7" fill="#76d8e3">OPEN-SOURCE TRUST OPERATIONS</text>
    <text x="1138" y="82" text-anchor="end" font-size="11" font-weight="720" letter-spacing="1.4" fill="#6f859f">SELF-HOSTED · CUSTOMER-OWNED</text>

    <text x="62" y="151" font-size="46" font-weight="860" letter-spacing="-1.8" fill="#f8fafc"><tspan>Collect.</tspan><tspan dx="12">Evaluate.</tspan><tspan dx="12" fill="url(#accent)">Prove.</tspan></text>
    <text x="64" y="187" font-size="17" font-weight="570" fill="#a8b5c7">Read-only evidence → deterministic control tests → immutable audit snapshots</text>

    <g transform="translate(62 214)">
      <rect width="184" height="34" rx="17" fill="#0d1a2d" stroke="#4f7cff"/>
      <text x="92" y="22" text-anchor="middle" font-size="12" font-weight="760" fill="#8db8ff">cloud + identity</text>
      <rect x="196" width="156" height="34" rx="17" fill="#0d1a2d" stroke="#30a8c9"/>
      <text x="274" y="22" text-anchor="middle" font-size="12" font-weight="760" fill="#77d9eb">code + CI</text>
      <rect x="364" width="172" height="34" rx="17" fill="#0d1a2d" stroke="#2dd4bf"/>
      <text x="450" y="22" text-anchor="middle" font-size="12" font-weight="760" fill="#79e4d6">evidence lakes</text>
      <rect x="548" width="174" height="34" rx="17" fill="#0d1a2d" stroke="#a78bfa"/>
      <text x="635" y="22" text-anchor="middle" font-size="12" font-weight="760" fill="#c4b5fd">GRC + agents</text>
    </g>

    <text x="62" y="281" font-size="11" font-weight="820" letter-spacing="1.8" fill="#7890b2">IMPLEMENTED READ-ONLY SOURCES</text>
{source_cards}

    <text x="62" y="410" font-size="12" font-weight="830" letter-spacing="1.6" fill="#76d8e3">CCF · {safeguard_count} safeguards</text>
    <text x="1138" y="410" text-anchor="end" font-size="12" font-weight="760" fill="#7890b2">{requirement_count} requirements · {framework_count} framework packs</text>
{chr(10).join(framework_pills)}
    <text x="62" y="489" font-size="10" font-weight="690" letter-spacing="0.55" fill="#657993">also HIPAA · PCI DSS · GDPR · EU AI Act · ISO 27017 · ISO 42001 · NIST AI RMF</text>

{stage_cards}
    <path d="M318 547h14" stroke="#6687ff" stroke-width="3" stroke-linecap="round"/>
    <path d="M592 547h14" stroke="#4d9ee4" stroke-width="3" stroke-linecap="round"/>
    <path d="M866 547h14" stroke="#30b8c7" stroke-width="3" stroke-linecap="round"/>

    <text x="62" y="608" font-size="11" font-weight="780" letter-spacing="1.35" fill="#7890b2">Console · API · CLI · MCP · CI</text>
    <text x="1138" y="608" text-anchor="end" font-size="11" font-weight="760" letter-spacing="1.2" fill="#657993">SAME VERIFIABLE JSON · ONE OPERATING LOOP</text>
  </g>
</svg>
"""


def main() -> int:
    OUTPUT.write_text(render_social_preview(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
